#
#  Config file
#
#  If you make changes to this file while your Jekyll server is running,
#  You'll need to restart your server.
# ---------------------------------------------------------------------

# Permalinks
permalink:        pretty

# Your site's full URL, e.g. "https://my-site.com" - leave this empty
# until you have/own a domain and a CNAME file.
# url:

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

# Site settings
title: Artifact Digital – Strategic Design Consultancy – Alex Leitch

description: > # this means to ignore newlines until "baseurl:"
  Future problems solved, fires put out

collections:
  projects:
    output: true
  
portfolio-categories:
  - Code
  - Exhibits
  - Speaking
  - Writing

author:
  name:    'Alex Leitch'
  twitter: aeleitch
  github:  pretentiousgit

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true

# Adding static pages through `_static/` folder
include: ['_static']
