const cards = {
    timeline: {
        // add some art - where are we now, are we travelling up or down?
        title: ["Best", "Better", "No Change", "Worse", "Worst"],
        timeline: [
          "A few years",
          "A decade",
          "30 years/You have kids",
          "60 years/Your kids have kids",
        ],
      },
  topic: [
    "Agriculture",
    "Bars and Cafes",
    "Blood Donation",
    "Charismatic Fauna",
    "Citizenship",
    "Construction",
    "Currency",
    "Decomposition",
    "Dentistry",
    "Education",
    "Energy",
    "Finance",
    "Fish Farming",
    "Fishing",
    "Food Production",
    "Forestry",
    "Gardens",
    "Governance",
    "Health",
    "Housing",
    "Hydroponics",
    "Industry",
    "Insects",
    "Intellectual Property",
    "Journalism",
    "Local Fauna",
    "Medicine",
    "Metal, Paper, Glass",
    "Mining",
    "Mushrooms",
    "Music",
    "News",
    "Organ Donation",
    "Outdoor Sports",
    "Pharmaceuticals",
    "Property Maintenance",
    "Public Space",
    "Renewables",
    "Resource Extraction",
    "Restaurants",
    "Solid Waste",
    "Spectator Sports",
    "Transportation",
    "Voting",
    "Vision",
    "Weather",
    "Romance",
    "Family Structure",
    "Obstetrics",
    "Long-Term Care",
  ],
      object: [
        "Artwork",
        "Beverage",
        "Book",
        "Bottle",
        "Box",
        "Building",
        "Candy",
        "Chatbot",
        "Clothing",
        "Document",
        "Event",
        "Factory",
        "Festival",
        "Flag",
        "Game",
        "Gift",
        "Headline",
        "Implant",
        "Instrument",
        "Jewellery",
        "Kit",
        "Law",
        "Lotion",
        "Machine",
        "Magazine",
        "Map",
        "Monument",
        "Passport",
        "Pill",
        "Plant",
        "Postcard",
        "Poster",
        "Product",
        "Prosthetic",
        "Relic",
        "Stream or Show",
        "Slogan",
        "Snack",
        "Song",
        "Souvenir",
        "Storage",
        "Statue",
        "Sticker",
        "Symbol",
        "Ticket",
        "T-Shirt",
        "Tattoo",
        "Tool",
        "Toy",
        "Utility",
        "Vehicle",
        "Video",
      ],
  audience: [
    "daycare",
    "preschool",
    "K-12",
    "teenagers ",
    "twentysomethings",
    "young parents",
    "middle-aged",
    "people older than 65",
    "elders",
    "immediate family",
    "extended family",
    "cultural group",
    "language group",
    "hobby group",
    "college alumnae org",
  ],
  limitation: [
    "Low Literacy",
    "Thumb and Little Finger Only",
    "Low Vision",
    "Low Hearing",
    "No Car",
    "Scent Migraines",
    "Motion Sickness",
    "Cannot Be In Car",
    "Cannot Use Public Transit",
    "Cannot Speak",
    "Weak Balance",
    "Colourblind, Red/Green",
    "Colour advantaged, purple",
    "Misophonia",
    "Hyperfocus",
    "Agoraphobia",
    "Fatigue",
  ],
  //   attitude: [],
 
};
